# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Web Deployment

on:
  push:
    branches: [ rkcd-jenkins ]
  pull_request:
    types: [labeled]
    branches: [ rkcd-jenkins ]

jobs:
  build:
    if: github.event.label.name == 'valid'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
  test:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    steps:
    - name: run some bash commands
      run: |
       echo what is in this directory
       ls -a
       
  Deploy: 
    if: github.event.label.name == 'invalid'
    runs-on: ubuntu-latest
    steps:
    - name:  deploy to tomcat
      run: curl -v -u tomcat:admin123 -T /home/runner/work/rkvprofile/rkvprofile/target/vprofile-v2.war 'ec2-13-127-11-34.ap-south-1.compute.amazonaws.com:8080//manager/text/deploy?path=/javamavenAction'
  
      
